// Mocks generated by Mockito 5.0.3 from annotations
// in rae_test/test/service/rae_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rae_test/api/rae_api.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [RaeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRaeApi extends _i1.Mock implements _i2.RaeApi {
  MockRaeApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> fetchData(String? word) =>
      (super.noSuchMethod(Invocation.method(#fetchData, [word]),
          returnValue: Future.value('')) as _i3.Future<String>);
}
